[keybindings]
esc = "back"
q = "back"

g = "scroll-to-top"
shift-g = "scroll-to-bottom"
k = "scroll-lines(-1)"
j = "scroll-lines(1)"
ctrl-u = "scroll-page(-1)"
ctrl-d = "scroll-page(1)"

ctrl-a = "job:check-all"
a = "job:check"
ctrl-c = "job:clippy-all"
c = "job:clippy"
alt-d = "job:doc-open"
d = "job:doc"
e = "job:ex"
ctrl-r = "job:run-long"
