require("mason").setup()
require("mason-lspconfig").setup {
    ensure_installed = {
        -- 'julials',
        -- 'clangd',
        'gopls',
        -- 'hls,',
        -- 'nil_ls',
        'rust_analyzer',
        -- 'qmlls',
        'tinymist',
        "cssls",
        "somesass_ls",
        "emmet_language_server",
        "html",
        "templ",
        -- "htmx",
        "lua_ls",
        "pylsp",
        "tombi",
        "templ",
        "ts_ls",
        "elixirls",
        -- "vue_ls",
        "svelte",
        "bashls",
        "jsonls",
        "dockerls",
        "docker_compose_language_service",
        "marksman",
        "yamlls",
        'tailwindcss',
        'ols',
        -- 'eslint-lsp',
        -- 'dartls',
        -- 'elp',
        -- "omnisharp"
        -- 'metals'
    },
}
