require("mason").setup()
require("mason-lspconfig").setup {
    ensure_installed = {
        -- 'julials',
        -- 'clangd',
        'gopls',
        -- 'hls,',
        -- 'nil_ls',
        'rust_analyzer',
        -- 'qmlls',
        'tinymist',
        "cssls",
        "emmet_language_server",
        "html",
        "lua_ls",
        "pylsp",
        "tombi",
        "templ",
        "vtsls",
        -- "vue_ls",
        "svelte",
        -- "bashls",
        "jsonls",
        -- "dockerls",
        -- "docker_compose_language_service",
        "marksman",
        "yamlls",
        'tailwindcss',
        -- 'eslint-lsp',
        -- 'dartls',
        -- 'elp',
        -- 'elixirls',
        -- "omnisharp"
        -- 'metals'
    },
}
